### ISSUE TITLE
On change is not getting called

### ISSUE THREAD

**Issue by nkovacic** [ryandrewjohnson/angular-editme#1]
Even after the value changes the on-change callback is not called.
Am I doing something wrong?

https://plnkr.co/edit/kOS22TerDWaRn87Gl4YU

**Comment by nkovacic** [comment]
@ryandrewjohnson any timeline for the merge of the pull requests?

**Comment by ryandrewjohnson** [comment]
I will try and get to the two smaller PRs this week. There is a 3rd larger PR that is waiting on updated unit tests from contributor since it would be a breaking change.

**Comment by ryandrewjohnson** [comment]
@nkovacic merged that PR from @compwright. Hopefully that fixes the issue you were having.

**Comment by nkovacic** [comment]
Fixed the the callback problem. Thank you :)
