### ISSUE TITLE
Problem when minifying

### ISSUE THREAD

**Issue by nkovacic** [ryandrewjohnson/angular-editme#6]
There was a problem with minifying because the injected angular services were not annotated using ng-annotate. 
Created a pull request #5 where I just inlined the services. Any other solution would require changing the build process (adding gulp or webpack).

**Comment by ryandrewjohnson** [comment]
Merged the PR and re-published. Please let me know if that fixes the issue.

**Comment by nkovacic** [comment]
A new release would be awesome :)

**Comment by ryandrewjohnson** [comment]
published new release - let me know if that fixes issue.

**Comment by nkovacic** [comment]
Added another #7 pull request. Missed one annotation.

**Comment by ryandrewjohnson** [comment]
@nkovacic just merged your PR and published another release. Let me know if that solves the minifying issue.

**Comment by nkovacic** [comment]
Thanks the issue is fixed :)
